#!/usr/bin/env sh

echo "[🐺 Husky][⏳ pre-push] Running safety checks before pushing..."

if ! node scripts/pre-push.js; then
  exit 1
fi

echo "[🐺 Husky][✅ pre-push] All checks passed. Proceeding..."

